In [1]:
import numpy as np

In [3]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [26]:
arr=np.array([4,8,11])
arr

array([ 4,  8, 11])

In [25]:
list_of_lists=[1,2,3], [4,5,6],[7,8,9]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(10,32)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31])

In [8]:
np.arange(10,83,8)

array([10, 18, 26, 34, 42, 50, 58, 66, 74, 82])

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [28]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [11]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.linspace(0,1,5) #evenly spaced

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [17]:
np.linspace(0,20,10,dtype=int) #nt solving the purpose but no eror

array([ 0,  2,  4,  6,  8, 11, 13, 15, 17, 20])

In [18]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [19]:
np.random.rand(2,4) #values range between 0 and 1np.random.randn

array([[0.99020687, 0.43602475, 0.26099407, 0.8385776 ],
       [0.77862215, 0.89277795, 0.03963551, 0.34714997]])

In [20]:
np.random.randn(2,4) #standard normal distribution - probability

array([[-0.69057582, -0.71450008,  1.13590341, -0.74866721],
       [ 1.12809833, -1.19397851, -1.32376268, -1.00627695]])

In [21]:
np.random.randint(0,10,15)

array([9, 5, 6, 2, 9, 6, 0, 7, 2, 3, 9, 6, 0, 6, 9])

In [31]:
np.random.randint(10,100,15)

array([17, 34, 45, 84, 38, 70, 16, 34, 28, 22, 21, 55, 96, 32, 70])

In [32]:
np.random.randint(20,56,100)

array([54, 20, 36, 36, 20, 32, 23, 31, 55, 47, 40, 33, 46, 55, 36, 49, 22,
       20, 47, 53, 27, 52, 51, 52, 42, 47, 35, 22, 51, 48, 23, 21, 49, 32,
       31, 43, 35, 38, 21, 49, 31, 33, 31, 45, 53, 43, 39, 51, 21, 53, 52,
       28, 28, 34, 20, 52, 22, 24, 38, 41, 21, 51, 41, 23, 21, 37, 55, 28,
       23, 32, 23, 37, 25, 33, 38, 26, 24, 45, 22, 28, 34, 24, 42, 40, 23,
       25, 40, 23, 41, 52, 32, 21, 28, 53, 51, 30, 40, 54, 44, 22])